const ITEMS = [
  {
    name: "Chop Plush & Bullet Whistle Set",
    game: "GTA V",
    category: "Hat",
    description:
      "Announced and released into the Rockstar Warehouse on 5th December 2013.\n\n A soft plush version of Chop with a removable leather collar and tag plus a secret stash pocket with a silver effect bullet whistle etched with GTA V text and logo. The plush is approximately 15cm high and 25cm long. \n\n\ Rarer to find in its original open-fronted retail box and many are missing the whistle (which was also sold separately). The leash and collar were also sold separately as a set.",
    year: "2013",
    rarity: "Rare",
    availability: "Sold in Stores",
    image: "images/chop.jpg",
    extraImages: [],
    link: "",
  },

  {
    name: "Pißwasser Beer Bottle",
    game: "Grand Theft Auto IV (2008)",
    category: "Mugs and Drinkware",
    description:
      "For the launch of Grand Theft Auto IV in 2008, Rockstar Games produced a real-world version of the fictional Pißwasser beer featured throughout the game.\n\nThe bottles were promotional merchandise rather than a standard retail product. They were distributed to people connected with the game's launch, including Rockstar staff, members of the press, media outlets, game testers and selected fansites. Individual bottles have since become highly sought-after collectibles.\n\nPerhaps the most interesting detail is that the bottles were not simply produced individually. 24-bottle crates of Pißwasser existed, with documented examples being distributed as promotional gifts. One particularly notable shipment reportedly consisted of six crates sent to UK gaming publication Computer and Video Games (CVG) as part of Rockstar's GTA IV promotional campaign.\n\nThe bottles were genuine physical beer bottles produced specifically for the promotion, complete with Pißwasser branding based on the fictional brewery from GTA IV. They were not included with the GTA IV Collector's Edition, despite occasional claims to the contrary.\n\nToday, surviving bottles and especially complete unopened crates are extremely rare, making the Pißwasser bottle one of the more unusual pieces of official Grand Theft Auto promotional merchandise from the GTA IV era.",
    year: "2008",
    rarity: "Very Rare",
    availability: "Given to Developers",
    image: "images/pisswasser.jpg",
    extraImages: ["images/crate.jpg"],
    link: "",
  },
  {
    name: "Flex Handcuffs",
    game: "Grand Theft Auto IV (2008)",
    category: "Other",
    description: "Flex handcuffs used to promote the release of GTA IV.",
    year: "2008",
    rarity: "Very Rare",
    availability: "Sold on Rockstar Website",
    image: "images/fc1.jpg",
    extraImages: ["images/fc2.jpg"],
    link: "",
  },
  {
    name: "Gift Wrap Paper",
    game: "Grand Theft Auto: San Andreas (2004)",
    category: "Wrapping Paper",
    description: "Gift wrap paper.",
    year: "2004",
    rarity: "Common",
    availability: "Sold on Rockstar Website",
    image: "images/GTA-SA-wrappingpaper1.jpg",
    extraImages: ["images/GTA-SA-wrappingpaper2.jpg"],["images/GTA-SA-wrappingpaper3.jpg"],
    link: "",
  },
];
